---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-readwrite
  namespace: biz-prod-oneops
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  - workfloweventbindings
  - workfloweventbindings/finalizers
  - workflowtemplates
  - workflowtemplates/finalizers
  - cronworkflows
  - cronworkflows/finalizers
  - clusterworkflowtemplates
  - clusterworkflowtemplates/finalizers
  - workflowtaskresults
  - workflowtaskresults/finalizers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - create
# 查询任务 LOGS 需要以下权限
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
# 下载 Artifact，需要读取 secrets "artifact-repositories" 资源
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - artifact-repositories
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-readwrite
  namespace: biz-prod-oneops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-readwrite
subjects:
- kind: ServiceAccount
  name: biz-prod-oneops-readwrite-limq
  namespace: argo
